// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlujZ09vCHGBDbA_huimrjJvvFRmeAM6s',
    appId: '1:782656858181:web:e9dfe12b88db19a305db2c',
    messagingSenderId: '782656858181',
    projectId: 'bidbuzz-e0cbd',
    authDomain: 'bidbuzz-e0cbd.firebaseapp.com',
    storageBucket: 'bidbuzz-e0cbd.appspot.com',
    measurementId: 'G-17R5QFW5Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQoZy8xRgW4VISS8-o0XOgFc_FblZmvDg',
    appId: '1:782656858181:android:a1d2f5218300f40e05db2c',
    messagingSenderId: '782656858181',
    projectId: 'bidbuzz-e0cbd',
    storageBucket: 'bidbuzz-e0cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcd2EFh_1Ay65t4-Mdz-nsZ4PY812xN7E',
    appId: '1:782656858181:ios:96b9e733368f815b05db2c',
    messagingSenderId: '782656858181',
    projectId: 'bidbuzz-e0cbd',
    storageBucket: 'bidbuzz-e0cbd.appspot.com',
    iosClientId: '782656858181-vtj75segq8ef9id3jcjjohakv1e5ruhm.apps.googleusercontent.com',
    iosBundleId: 'com.sodomizer.bidbuzz.bidbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcd2EFh_1Ay65t4-Mdz-nsZ4PY812xN7E',
    appId: '1:782656858181:ios:9ee0e75e797f5b9705db2c',
    messagingSenderId: '782656858181',
    projectId: 'bidbuzz-e0cbd',
    storageBucket: 'bidbuzz-e0cbd.appspot.com',
    iosClientId: '782656858181-cjs3ag0rs0bljvup8g50lcmdj1u6nle2.apps.googleusercontent.com',
    iosBundleId: 'com.sodomizer.bidbuzz.bidbuzz.RunnerTests',
  );
}
